
title: Ken Garber
email: kengarber98@gmail.com
description: >-
  Ken Garber. Boston University student, Software Engineer, 
  technology enthusiast. Visit my site to learn more.
baseurl: "/"
url: "http://kgarber.com"
markdown: kramdown
